"""Creacion inicial de tablas paciente y cita

Revision ID: 0d2ecc5df528
Revises: 
Create Date: 2025-08-13 00:00:38.945896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d2ecc5df528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rut', sa.String(length=12), nullable=False),
    sa.Column('nombre', sa.String(length=128), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paciente_rut'), ['rut'], unique=True)

    op.create_table('cita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.String(length=128), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('motivo', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cita')
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paciente_rut'))

    op.drop_table('paciente')
    # ### end Alembic commands ###
