"""Eliminar client_id y client_secret de Credencial

Revision ID: 116e490400f2
Revises: db92c6a88277
Create Date: 2025-08-14 14:53:56.216315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116e490400f2'
down_revision = 'db92c6a88277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.drop_column('client_secret')
        batch_op.drop_column('client_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.VARCHAR(length=2048), nullable=False))
        batch_op.add_column(sa.Column('client_secret', sa.VARCHAR(length=2048), nullable=False))

    # ### end Alembic commands ###
