"""Forzar detección de cambios en Credencial

Revision ID: 53a56f39f484
Revises: 116e490400f2
Create Date: 2025-08-14 16:07:16.050740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a56f39f484'
down_revision = '116e490400f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_temp_column', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.drop_column('_temp_column')

    # ### end Alembic commands ###
