"""Eliminar client_id y client_secret de Credencial (final)

Revision ID: 7b4ebf4595ba
Revises: 53a56f39f484
Create Date: 2025-08-14 16:11:11.999235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b4ebf4595ba'
down_revision = '53a56f39f484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.drop_column('_temp_column')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_temp_column', sa.VARCHAR(length=10), nullable=True))

    # ### end Alembic commands ###
