"""Add user_id to Credencial model

Revision ID: a6fb98b09cb5
Revises: 06d4e2a6bfaf
Create Date: 2025-08-15 12:39:47.826327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6fb98b09cb5'
down_revision = '06d4e2a6bfaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_credencial_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credencial', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credencial_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###