"""añadir tabla credencial

Revision ID: db92c6a88277
Revises: 0d2ecc5df528
Create Date: 2025-08-13 14:10:30.137613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db92c6a88277'
down_revision = '0d2ecc5df528'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credencial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_doctor', sa.String(length=128), nullable=False),
    sa.Column('token', sa.String(length=2048), nullable=False),
    sa.Column('refresh_token', sa.String(length=2048), nullable=False),
    sa.Column('token_uri', sa.String(length=2048), nullable=False),
    sa.Column('client_id', sa.String(length=2048), nullable=False),
    sa.Column('client_secret', sa.String(length=2048), nullable=False),
    sa.Column('scopes', sa.String(length=2048), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre_doctor')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credencial')
    # ### end Alembic commands ###
